### PR TITLE
Add webpack production

### PR DESCRIPTION
**Pull request by ykushch**
Additions:
* webpack-production config file was added
* webpack-dev-server config added but currently is in progress (need to bind to backend in order to make hot-reload)

Removals:
* gulp routine

### CODE REVIEW

**Comment by deepu105** [comment]
Ok merging this coz I trust you on this :)

**Comment by ykushch** [comment]
I warned that it is work in progress :)

**Comment by deepu105** [comment]
I know, but the entire module is a WIP so its OK :)

**Comment by deepu105** [comment]
You can commit to the master directly if you want. Once we have our first release then we can follow process of Doing PR and reviews of each others commit :)

**Comment by deepu105** [comment]
what is your NPM user id , ill add you as collaborator on the NPM project as well

**Comment by ykushch** [comment]
Sure. Then I'll commit directly to master. 
Regarding to NPM user id: @ykushch.

**Pull request merged**
