### PR TITLE
Fix basic jhipster-react project generation

### PR DESCRIPTION
**Pull request by jlehmer**
Added the creation of a .yo-rc.json file to meet the requirements of the jhipster:modules reference.

### CODE REVIEW

**Comment by ykushch** [comment]
What do you think @deepu105?

**Comment by deepu105** [comment]
Not how I would want it to work but given I dont have enough time to work on this ill merge it. Once JHipster ng2 release is stable I'm gonna spend more time here to bring this generator upto speed and implement all the pages with JH4 as backend

**Comment by jlehmer** [comment]
@deep105, just curious how would you prefer this work?

**Comment by deepu105** [comment]
When you use a yeoman generator it automatically creates a .yo-rc file for that generator and since I'm composing the JHipster generator here it should have done that and additional data from this generator is also appended to the same file. So there might be some bug here so I would fix that so that the file is automatically created.

**Pull request merged**
